### ISSUE TITLE
Change Error/Status Messages from plain text to XML 

### ISSUE THREAD

**Issue by Joeran** [Mr-DLib/mdl-server#63]
the current error messages are plain text, e.g.
https://api.mr-dlib.org/v1/documents/gesis-smarth-00000003284/related_documents/

> No DB Entry: gesis-smarth-00000003284

However, they should be in XML, with error codes. It is rather important to implement this soon, so our partner can use the right error codes from the beginning.

suggestion for XML

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"? status_code="status_code">
 <status_details>
   <status_message>"..."</status_message>
   <debug_details><![CDATA[  debug details with special characters - important for error 520   ]]></debug_details>
 </status_details>
```

Possible statuses:
- 200 - OK
- 204 - No related documents found (we return an empty list, or just nothing?)
- 400 - Invalid Request/URL
- 404 - Requested document does not exist in database
- 520 - Unknown error

This means, also the standard response - i.e. when related documents are returned - should be extended by a status_code="200" without status_details though.

**Comment by SophieSiebert** [comment]
https://api.mr-dlib.org/dev/documents/mrdlib/related_documents

**Comment by Joeran** [comment]
Currently:

```
<mrdlib>
  <status_details>
    <status>
        <details>Document id: mrdlib</details>
        <id>2</id>
        <status_code>204</status_code>
         <title>No related documents found</title>
    </status>
  </status_details>
</mrdlib>
```

please change to

```
<mr-dlib>                                                                   // add '-'
  <status_details>
    <status_detail code="$status_code">
        <status_message lang="en">Document id: $doc_id not found</details>
        <debug_details><![CDATA[  debug details with special characters - important for error 520   ]]>  </debug_details>     // make this optional (show only if a global variable 'debug' is TRUE
    </status_detail>
  </status_details>
</mr-dlib>
```

**Comment by SophieSiebert** [comment]
Should be ok. Please check, if Error Messages are like you want them to be :)

**Comment by SophieSiebert** [comment]
200  -> ok
404 -> ok
204 -> ok
520 -> ok

400 -> not ok
