### ISSUE TITLE
Bug: Documents without abstracts do not have related documents

### ISSUE THREAD

**Issue by Joeran** [Mr-DLib/mdl-server#68]
documents that have no abstract in solr do not return related documents in the webservice
https://api.mr-dlib.org/v1/documents/gesis-smarth-0000003284/related_documents/
![image](https://cloud.githubusercontent.com/assets/2410381/17123646/f0f2969e-531f-11e6-8289-0d4af9e2778a.png)

**Comment by SophieSiebert** [comment]
Decreased Solr MLT settings to 

> mintf = 1

MinTF 2 leads to not recognizing terms which occur only once -> which normally happens when you only have a title
