### ISSUE TITLE
Abstracts are missing for some documents

### ISSUE THREAD

**Issue by Joeran** [Mr-DLib/mdl-server#69]
for some documents there is no abstract in the database
https://api.mr-dlib.org/v1/documents/gesis-smarth-0000003284/related_documents/

in the xml file there is a description though

`<field name="description_de_txt_mv">Der Frankfurter Arbeitskreis Trauma und Exil (FATRA e.V.) gründete sich 1993 rund um das Projekt einer sozialpsychiatrischen Sprechstunde in einer Flüchtlingsunterkunft für bosnische Flüchtlinge in Hessen. Zwischen 1995 und 2004 unterhielt der Verein eine Behandlungseinrichtung für Flüchtlinge und Folteropfer in Frankfurt am Main, in der zeitweise mehr als 200 Patienten jährlich behandelt und beraten wurden. Aufgrund der vielen Nachfragen nach psychotherapeutischen Behandlungen von traumatisierten Flüchtlingen war diese Sprechstunde damals sehr überlastet.</field>`

\GESIS_Datenexport\2016-03\sowiport-gesissmart\gesissmart\solr-export-10.xml

**Comment by SophieSiebert** [comment]
false alarm
