### ISSUE TITLE
error 500 is not caught

### ISSUE THREAD

**Issue by Joeran** [Mr-DLib/mdl-server#73]
this error should not appear:
https://api.mr-dlib.org/v1/documents/gesis-smarth-0000003284/related_documents/
![image](https://cloud.githubusercontent.com/assets/2410381/17430274/213e66dc-5b2e-11e6-92cb-49cd1225aa4e.png)

rather it should be catched . can we do this?

**Comment by SophieSiebert** [comment]
Das liegt daran, dass der Fehler außerhalb meines Codes auftaucht. Halt 
vom Container außendrum, - Tomcat. Ich glaube nicht, dass wir den 
abfangen können, wir können nur die Seite ersetzen. Der Fehler sagt, 
dass er die Webapp nicht deployen kann.

Am 05.08.2016 um 17:01 schrieb Joeran Beel:
