### ISSUE TITLE
Add a "mdl" before each css class name

### ISSUE THREAD

**Issue by Joeran** [Mr-DLib/mdl-server#75]
Currently, the html snippet looks like this

`<span class='mdl-title'>Flüchtlinge in Deutschland</span>. <span class='authors'>Wolf B. Emminghaus;/span>. <span class='journal'>Sozial extra</span>. <span class='volume_and_number'>6:66</span>. <span class='year'>2008</span>`

and the class names are
- mdl-title
- authors
- journal
- volume_and_number

However, the class names should rather be
- mdl-title
- mdl-authors
- mdl-journal
- mdl-volume_and_number

**Comment by SophieSiebert** [comment]
I guess mdl-year, too?

**Comment by Joeran** [comment]
yes, for all CSS tags.
