### ISSUE TITLE
Fix 500 Error

### ISSUE THREAD

**Issue by Joeran** [Mr-DLib/mdl-server#77]
https://api.mr-dlib.org/dev/documents/gesis-smarth-0000003284/related_documents/
I was just sending many requests to the api (about one every second for 3 minutes), and now I am getting this error all the time:

![image](https://cloud.githubusercontent.com/assets/2410381/17538786/8b7f3cb6-5ee3-11e6-8cbb-4788bcf8e7f2.png)

@MillahMau  can you somehow see in the logs what caused this error, and fix it?

**Comment by SophieSiebert** [comment]
Thats fine. I just fixed the 500 Tomcat Error Page. :P

**Comment by SophieSiebert** [comment]
I hope i fixed it with fixing the Database Connection. If it runs for a day smoothly I will close this.
